manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson #https://github.com/ErikBPF
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pmw3610-aml
      import: feat/pointers-move-scroll # app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config
